### ISSUE TITLE
Usage with diamond?

### ISSUE THREAD

**Issue by charlesfoster** [Arcadia-Science/2023-nr-clustering#10]
Hi,

Thanks for providing this resource. I hoped to use your version of the clustered nr database to assign taxonomy to contigs using diamond. However, I'm having a bit of trouble trying to figure out which files to use in the `diamond makedb` command.

In the diamond wiki, there are the following instructions:

```
Makedb options
--in <file>

Path to the input protein reference database file in FASTA format (may be gzip compressed). If this parameter is omitted, the input will be read from stdin.

--db/-d <file>

Path to the output DIAMOND database file.

--taxonmap <file>

Path to mapping file that maps NCBI protein accession numbers to taxon ids (gzip compressed). This parameter is optional and needs to be supplied in order to provide taxonomy features. The file can be downloaded from NCBI: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.FULL.gz

Versions older than v2.0.7 only support the reduced mapping file: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz

A custom file following the same format may be supplied here. Note that the first line of this file is assumed to contain headings and will be ignored.

--taxonnodes <file>

Path to the nodes.dmp file from the NCBI taxonomy. This parameter is optional and needs to be supplied in order to provide taxonomy features. The file is contained within this archive downloadable at NCBI: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdmp.zip.

--taxonnames <file>

Path to the names.dmp file from the NCBI taxonomy. This parameter is optional and needs to be supplied in order to provide taxonomy features. The file is contained within this archive downloadable at NCBI: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdmp.zip.
```

Are any of the files you provide compatible/drop-in replacements for `prot.accession2taxid.FULL.gz`, `nodes.dmp`, and `names.dmp`?

Thanks

**Comment by elizabethmcd** [comment]
Hello! This documentation for our metagenomics workflow for preparing DIAMOND databases along with taxonomy information might answer your question: https://github.com/Arcadia-Science/metagenomics/blob/main/docs/usage.md#diamond-database 
For this example we used the uniref90 database but I think the files you need for your case will be the same. Let me know if that doesn't work!

**Comment by charlesfoster** [comment]
Thanks for the reply. So, just to confirm based on the tutorial link you provided, for the `--taxonmap` , `--taxonnodes` and `--taxonnames` arguments I would download and run the following:

```
# taxonomy files
wget https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdmp.zip
wget https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.FULL.gz

# unzip files
gunzip taxdmp.zip
tar -xzvf prot.accession2taxid.FULL.gz
```

Is it correct the the only file I need to download from https://osf.io/tejwd/ is "nr_rep_seq.fasta.gz".?

Finally, would I then run the following?

`diamond makedb --in nr_rep_seq.fasta.gz --taxonmap prot.accession2taxid.FULL --taxonnodes taxdmp/nodes.dmp --taxonnames taxdmp/names.dmp -d nr_rep_seq.dmnd`

**Comment by elizabethmcd** [comment]
I believe this should work with swapping out the uniref database for the NR one! If not let us know!

**Comment by charlesfoster** [comment]
Great - I tried it out and it worked perfectly. Thanks. Originally I just wasn't sure whether custom versions of the prot.accession2taxid.FULL file would be needed for the clustered NR db (vs the full db), but turns out the answer to that is no.
